####################################################################################
# docker-compose file for Apache Guacamole
# created by PCFreak 2017-06-28
#
# Apache Guacamole is a clientless remote desktop gateway. It supports standard
# protocols like VNC, RDP, and SSH. We call it clientless because no plugins or
# client software are required. Thanks to HTML5, once Guacamole is installed on
# a server, all you need to access your desktops is a web browser.
####################################################################################
#
# (1)
#  DB-Init script is in './init/initdb.sql' it has been created executing
#  'docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgresql > ./init/initdb.sql'
#  once.
#  DATA-DIR       is in './data'
#  If you want to change the DB password change all lines with 'POSTGRES_PASSWORD:' and
#  change it to your needs before first start.
#  To start from scratch delete './data' dir completely
#  './data' will hold all data after first start!
#  The initdb.d scripts are only executed the first time the container is started
#  (and the database files are empty). If the database files already exist then the initdb.d
#  scripts are ignored (e.g. when you mount a local directory or when docker-compose saves
#  the volume and reuses it for the new container).
#
#  !!!!! MAKE SURE your folder './init' is executable (chmod +x ./init)
#  !!!!! or 'initdb.sql' will be ignored!
#
# The initial login to the guacamole webinterface is:
#
#     Username: guacadmin
#     Password: guacadmin
#
# Make sure you change it immediately!
#####################################################################################

# networks
# create a network 'guacnetwork_compose' in mode 'bridged'
secrets:
  # create with 'pwgen -ycsB --remove-chars=\"\'\\\/@\` 60 1 > ./secrets/postgres_password'
  POSTGRES_PASSWORD:
    file: ./secrets/postgres_password
  POSTGRES_USER:
    file: ./secrets/postgres_user

networks:
  guacnetwork_compose:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw
  # postgres
  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: "/run/secrets/POSTGRES_PASSWORD"
      POSTGRES_USER_FILE: "/run/secrets/POSTGRES_USER"
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    image: postgres:15.2-alpine
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ./data:/var/lib/postgresql/data:Z

  # guacamole
  guacamole:
    container_name: guacamole_compose
    group_add:
      - "1000"
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: "/run/secrets/POSTGRES_PASSWORD"
      POSTGRES_USER_FILE: "/run/secrets/POSTGRES_USER"
      RECORDING_SEARCH_PATH: /record
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    image: guacamole/guacamole
    networks:
      - guacnetwork_compose
    volumes:
      - ./record:/record:rw
    ports:
      ## enable next line if not using nginx
      ##    - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.
      ## enable next line when using nginx
      - 8080/tcp
    restart: always

  ########### optional ##############
  # nginx
  nginx:
    container_name: nginx_guacamole_compose
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
      - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
    ports:
      - 8443:443
    networks:
      - guacnetwork_compose
####################################################################################
